
product_database = [
    {
        "id": 1,
        "title": "파이썬 완벽 가이드",
        "description": "파이썬 프로그래밍 언어에 대한 전반적인 안내서입니다.",
        "created_at": "2022-01-01",
        "updated_at": "2022-01-02",
        "seller": "도서출판 길벗",
        "category": "프로그래밍",
        "tag": ["파이썬", "프로그래밍"],
        "sell_count": 150,
        "thumbnail": "https://picsum.photos/200/300?1",
        "like_count": 25,
        "like_user": [101, 102, 103],
        "price": 32000,
        "stock": 20
    },
    {
        "id": 2,
        "title": "자바의 정석",
        "description": "자바 프로그래밍 학습을 위한 최고의 입문서입니다.",
        "created_at": "2022-02-15",
        "updated_at": "2022-02-16",
        "seller": "도서출판 남궁성",
        "category": "프로그래밍",
        "tag": ["자바", "프로그래밍"],
        "sell_count": 200,
        "thumbnail": "https://picsum.photos/200/300?2",
        "like_count": 30,
        "like_user": [104, 105, 106],
        "price": 35000,
        "stock": 15
    },
    {
        "id": 3,
        "title": "클린 코드",
        "description": "코드 품질을 높이고 유지보수를 용이하게 하는 기법에 대해 소개합니다.",
        "created_at": "2022-03-10",
        "updated_at": "2022-03-11",
        "seller": "도서출판 프로그래밍 인사이트",
        "category": "소프트웨어 공학",
        "tag": ["소프트웨어 공학", "코드 품질"],
        "sell_count": 300,
        "thumbnail": "https://picsum.photos/200/300?3",
        "like_count": 45,
        "like_user": [107, 108, 109],
        "price": 38000,
        "stock": 10
    },
    {
        "id": 4,
        "title": "리팩터링 2판",
        "description": "소프트웨어 구조를 개선하는 리팩터링 기법을 다룹니다.",
        "created_at": "2022-04-20",
        "updated_at": "2022-04-21",
        "seller": "도서출판 오라일리",
        "category": "소프트웨어 공학",
        "tag": ["리팩터링", "소프트웨어 공학"],
        "sell_count": 120,
        "thumbnail": "https://picsum.photos/200/300?4",
        "like_count": 20,
        "like_user": [110, 111, 112],
        "price": 40000,
        "stock": 5
    },
    {
        "id": 5,
        "title": "알고리즘 문제 해결 전략",
        "description": "다양한 알고리즘 문제 해결 방법을 체계적으로 배울 수 있습니다.",
        "created_at": "2022-05-05",
        "updated_at": "2022-05-06",
        "seller": "도서출판 인사이트",
        "category": "프로그래밍",
        "tag": ["알고리즘", "문제 해결"],
        "sell_count": 180,
        "thumbnail": "https://picsum.photos/200/300?5",
        "like_count": 35,
        "like_user": [113, 114, 115],
        "price": 45000,
        "stock": 8
    },
    {
        "id": 6,
        "title": "Do it! 자바스크립트 입문",
        "description": "자바스크립트 기초부터 실전 활용까지 배울 수 있는 입문서입니다.",
        "created_at": "2022-06-01",
        "updated_at": "2022-06-02",
        "seller": "도서출판 이지스퍼블리싱",
        "category": "프로그래밍",
        "tag": ["자바스크립트", "웹 개발"],
        "sell_count": 90,
        "thumbnail": "https://picsum.photos/200/300?6",
        "like_count": 15,
        "like_user": [116, 117, 118],
        "price": 27000,
        "stock": 12
    },
    {
        "id": 7,
        "title": "유닉스 프로그래밍 환경",
        "description": "유닉스 시스템에서의 소프트웨어 개발 환경을 다룹니다.",
        "created_at": "2022-07-07",
        "updated_at": "2022-07-08",
        "seller": "도서출판 사이텍미디어",
        "category": "시스템 프로그래밍",
        "tag": ["유닉스", "시스템 프로그래밍"],
        "sell_count": 70,
        "thumbnail": "https://picsum.photos/200/300?7",
        "like_count": 10,
        "like_user": [119, 120, 121],
        "price": 30000,
        "stock": 6
    }
]
